- 
  name: to install and configure LAMP stack
  hosts: target1
  gather_facts: false
  become: yes
  tasks:
    - name: 'Install Firewall'
      yum: 
        name: firewalld
        state: installed

    - name: 'Start Firewall'
      service: 
        name: firewalld
        state: started

    - name: 'Enable Firewall'
      systemd: 
        name: firewalld
        enabled: yes

    - name: 'Install SQL server'
      yum: 
        name: mariadb-server
        state: installed

    - name: 'Start SQL Server'
      service: 
        name: mariadb
        state: started

    - name: 'Enable SQL server'
      systemd: 
        name: mariadb
        enabled: yes

    - name: 'Configure firewall for DB'
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp

    - name: 'Reload Firewall'
      systemd:
        name: firewalld 
        state: reloaded

    - name: 'Install PyMySQL package'
      pip: 
        name: PyMySQL
        state: present

    - name: 'Create DB'
      mysql_db:
        name: ecomdb 
        state: present
      register: db_exists

    - name: 'Create DB user'
      mysql_user:
        name: ecomuser 
        state: present
        password: ecompassword
        priv: "ecomdb.*:ALL"

    - name: 'Flush SQL Privileged'
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
    
    - name: 'Execute sql query'
      community.mysql.mysql_query:
        login_db: ecomdb
        query:
          - CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
          - INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");
      when: db_exists.changed

    - name: 'Install http and php'
      yum: 
        name: 
          - httpd 
          - php
          - php-mysqlnd
        state: present
    
    - name: 'Configure firewall for HTTP'
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp

    - name: 'Reload Firewall'
      systemd:
        name: firewalld 
        state: reloaded

    - name: 'Replace index.html with index.php'
      replace: 
        path: /etc/httpd/conf/httpd.conf
        regexp: index.html
        replace: index.php

    - name: 'Start http'
      service: 
        name: httpd
        state: started

    - name: 'Enable httpd'
      systemd: 
        name: httpd
        enabled: yes

    # - name: 'Get web code'
    #   command: git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/

    - name: 'Clone code from git'
      git: 
        repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
        dest: '/var/www/html/'
        force: yes
    

    - name: 'Replace ip with localhost'
      replace: 
        path: /var/www/html/index.php
        regexp: 172.20.1.101
        replace: localhost